version: '2'
services:
  catsauction_db:
    image: postgres:12-alpine
    container_name: catsauction-db
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=catsauction
      - POSTGRES_PASSWORD=catsauction
      - POSTGRES_DB=catsauction
    volumes:
      - catsauction_db_data:/var/lib/postgresql/data/

  catsauction_api:
    restart: "no"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - catsauction_db
    environment:
      - CATSAUCTION_DB_URI=postgresql://catsauction:catsauction@catsauction-db:5432/catsauction

volumes:
  catsauction_db_data:
