import datetime
from random import randint, choice

from psycopg2.extras import execute_batch
import psycopg2 as psycopg


# Init


INIT_SQL = '''DROP TABLE IF EXISTS events;
CREATE TABLE events (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid int4 NOT NULL,  -- user id
    date timestamp NOT NULL
);'''

conn = psycopg.connect(
    database='logictasks', user='dev', password='dev',
    host='localhost', port=5432)
cur = conn.cursor()
cur.execute(INIT_SQL)


# Generate data


def gen_values(count: int, user_count=10, max_days_dx=30):
    uids = list(range(user_count))
    from_date = datetime.datetime.now()
    for _ in range(count):
        date = from_date - datetime.timedelta(days=randint(0, max_days_dx), hours=randint(0, 23))
        yield choice(uids), date


execute_batch(
    cur,
    'INSERT INTO events (uid, date) VALUES (%s, %s)',
    gen_values(300)
)
conn.commit()


# Test


with open('solution.sql') as fp:
    cur.execute(fp.read())
print(cur.fetchall())  # uid, start_date, days
